import Foundation

/// Something the user copied, kept by clipboard history (D-020). Only on this Mac, never logged (R-SEC-6).
public struct ClipboardEntry: Codable, Equatable, Identifiable, Sendable {
    public enum Kind: String, Codable, Sendable { case text, image }

    public var id: String
    public var kind: Kind
    public var text: String?
    /// For an image: its PNG file's name in the clipboard folder.
    public var imageFile: String?
    /// Recognizes the same content copied again.
    public var digest: String
    public var date: Date
    /// The app that was in front when it was copied.
    public var source: String?

    public init(id: String = UUID().uuidString, kind: Kind, text: String? = nil, imageFile: String? = nil,
                digest: String, date: Date, source: String? = nil) {
        self.id = id
        self.kind = kind
        self.text = text
        self.imageFile = imageFile
        self.digest = digest
        self.date = date
        self.source = source
    }

    public var isValid: Bool {
        switch kind {
        case .text: return !(text ?? "").isEmpty
        case .image: return imageFile.map { !$0.isEmpty && !$0.contains("/") && !$0.hasPrefix(".") } ?? false
        }
    }
}

public enum ClipboardHistory {
    public static let maximum = 50
    /// Longer text is not kept, so history never holds a whole document.
    public static let maximumTextLength = 100_000
    public static let maximumImageBytes = 20_000_000

    /// Pasteboard types that mark content history must skip (nspasteboard.org): passwords and other secrets,
    /// content meant to vanish, and content an app generated by itself (R-WID-6). Copied files are not kept either.
    public static let skippedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType",
        "public.file-url"
    ]

    public static func shouldSkip(types: [String]) -> Bool { !skippedTypes.isDisjoint(with: types) }

    /// Puts `entry` first. The same content copied again moves up instead of appearing twice. Returns the entries
    /// that left the history, so their image files can be deleted.
    public static func adding(_ entry: ClipboardEntry, to entries: [ClipboardEntry]) -> (entries: [ClipboardEntry], removed: [ClipboardEntry]) {
        let repeated = entries.filter { $0.digest == entry.digest }
        let kept = [entry] + entries.filter { $0.digest != entry.digest }
        return (Array(kept.prefix(maximum)), repeated + kept.dropFirst(maximum))
    }

    /// Reads stored entries, skipping those that cannot be read or are not valid (R-COMPAT-3).
    public static func decode(_ data: Data?) -> [ClipboardEntry] {
        guard let data, let list = try? JSONDecoder().decode([Lossy<ClipboardEntry>].self, from: data) else { return [] }
        return Array(list.compactMap(\.value).filter(\.isValid).prefix(maximum))
    }
}
